language: generic
os:
  - linux

jobs:
  include:
    - stage: Build
      name: Build td
      script:
        - sudo apt update -y
        - gcc --version
        - sudo apt install -y tree gperf
        - go get github.com/ericchiang/pup
        - echo 'https://$GH_TOKEN@github.com' > ~/.git-credentials
        - git config --global credential.helper store
        - docker --version
        - docker ps
        - docker images
        - BIN_PATH=$(dirname $(readlink -f $0))
        - docker run --rm -dit --name alpine -v $BIN_PATH:/source alpine:3.9
        - ALPINE="docker exec -it alpine "
        - $ALPINE apk update
        - $ALPINE apk add gcc g++ cmake make zlib-dev openssl git
        - $ALPINE mkdir /source/build
        - $ALPINE cd /source/build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .
        - sh -f ./build.sh

