
language: generic
branches:
  only:
    - build
jobs:
  include:
    - stage: Build
      name: Build td
      script:
        - sudo apt update
        - sudo apt install -y tree
        - go get github.com/ericchiang/pup
        - sh -f ./build.sh

