language: generic
os:
  - linux

jobs:
  include:
    - stage: Build
      name: Build td
      script:
        - sudo apt update -y
        - gcc --version
        - sudo apt install -y tree gperf
        - go get github.com/ericchiang/pup
        - echo 'https://$GH_TOKEN@github.com' > ~/.git-credentials
        - git config --global credential.helper store
        - docker --version
        - docker ps
        - docker images
        - TD_PATH=/tmp/td
        - git clone https://github.com/tdlib/td.git $TD_PATH
        - mkdir $TD_PATH/build
        - touch $TD_PATH/build/a.txt
        - ls $TD_PATH/build
        - docker run --rm -dit --name alpine -v $TD_PATH:/source alpine:3.9
        - ALPINE="docker exec -it alpine"
        - $ALPINE apk update
        - $ALPINE apk add gcc g++ cmake make zlib-dev openssl git
        - $ALPINE ls /source
        - $ALPINE ls /source/build
        - $ALPINE cd /source/build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .
        - sh -f ./build.sh

