language: generic
os:
  - linux

branches:
  only:
    - build
    - stable

jobs:
  include:
    - stage: Build
      name: Build td
      script:
        - sudo apt update -y
        - gcc --version
        - sudo apt install -y tree gperf
        - go get github.com/ericchiang/pup
        - sh -f ./build.sh

