version: 2.1


jobs:
  build:
    docker:
      - image: alpine:3.9
    steps:
      - checkout
      - run: echo $GH_TOKEN
      - run: apk update
      - run: apk add gcc g++ cmake make zlib-dev openssl git
      - run: mkdir build && cd build
      - run: cmake -DCMAKE_BUILD_TYPE=Release ..
      - run: cmake --build .


workflows:
  version: 2
  dylib-workflow:
    jobs:
      - build:
        context: GH
        filters:
          branches:
            only: build


