version: 2.1


jobs:
  build:
    docker:
      - image: alpine:3.9
    steps:
      - checkout
      - run: apk update
      - run: apk add gcc g++ cmake make zlib-dev openssl git
      - run: mkdir build
      - run: cd build
      - run: pwd
      - run: ls -l && ls ../ -l
      - run: cmake -DCMAKE_BUILD_TYPE=Release ..
      - run: cmake --build .
      - store_artifacts:
          path: build/

workflows:
  version: 2
  dylib-workflow:
    jobs:
      - build:
          context: GH
          filters:
            branches:
              only: build


