name: CI

on:
  push:
    branches:
    - build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update system
      run: sudo apt update -y
    - name: Install dependencies
      run: sudo apt install -y tree gperf
    - name: Checkout
      uses: actions/checkout@build
    - name: Do build
      run: |
        pwd
        ls -l
        ls -l ../
        ls -l ../../
