name: CI

on:
  push:
    branches:
    - build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update system
      run: apt update -y
    - name: Install dependencies
      run: apt install -y tree gperf
    - name: Do build
      run: sh -f build_github.sh
